### ISSUE TITLE
Issue #32 still not fixed.

### ISSUE THREAD

**Issue by ghost** [MGeymer/LDYOM#71]

**Comment by cherdaq** [comment]
Stop creating hundreds of empty issues, thank you

**Comment by Anime-Guy2000** [comment]
Stop making bs comment that don't add anything to the subject.

**Comment by cherdaq** [comment]
> Stop making bs comment that doesn't add anything to the subject. Edit: The issues aren't empty. They are actual "issues", unlike your useless comment.

I see you are very polite, good on you. I'm not on tight terms with the creator but that only makes me wish less that Sergei actually spends his time and effort on the mod only to release it for people like you.
Does _your_ comment adds anything to the subject? If you're so worried about efficient dialogue, go to C:DDA devcord or something similiar. 
LDYOM is a small project currently maintained by one single person. There is literally no serious reason to solve everything exclusively through Github as you can just contact him on directly on Telegram & Discord, platforms where he actually appears online more. 
Alternatively, you can organize everything into one big issue that I can unsubscribe from freely instead of creating heaps of issues that clutter up my e-mail and e-mails of any other person subscribed to the repository.
Thank you and have a soft diarrhea.

**Comment by Anime-Guy2000** [comment]
@cherdaq Firstly, who the hell are you? Secondly, I ain't forcing your husband, _Sergei_ to fix these issues. Third, didn't ask for your advice on what to join or not & Fourth, I won't be making accounts just 'cause you, an irrelevant person, doesn't like it.
Oh, Its cluttering your inbox? Well boo-hoo maybe you should like turn off notifications for GitHub altogether or beg your husband to remove you as a contributor, you have hardly contributed anything to the "project". On a legit note, if you really wanted to not receive notifs via email you could have turned it off, but instead you decided to ping me & cry here.
Have a hard stool ;)

**Comment by GeTechG** [comment]
Sergei, it's me. And I think we should end this discussion. I must admit that so many issues are not very informative. It is better to write the problem exactly in the description, just as you have made checkboxes also problems. Because there are a lot of issues and I'm starting to get confused myself.

**Comment by Anime-Guy2000** [comment]
Do you really know this clown? He hasn't really helped with anything in the past 2 YEARS and only now keeps crying about his inbox getting filled. Questioned my _"PoLiTeNEsS"_ and isn't any better himself.

> I must admit that so many issues are not very informative.

Why not a single time have you mentioned this before to me? @GeTechG If you have any problem with me talk directly to me. I don't want no other irrelevant person, who hasn't contributed to anything in over 2yrs, tell me bs.

**Comment by GeTechG** [comment]
> Why not a single time have you mentioned this before to me?

I didn't ask anyone to write. I respond to you as I get comfortable. It wasn't that important before, but now I'm telling you this.

**Comment by cherdaq** [comment]
> He hasn't really helped with anything in the past 2 YEARS
> I don't want no other irrelevant person, who hasn't contributed to anything in over 2yrs, tell me bs.

Why do you keep bringing it up? I contributed to repo where I could, when I could, and if there isn't anything I can help with, it's better to stay aside. I've been in touch with GTG ever since through the platforms you dismiss (linked at the end of README!). I tried warming up some hype at a GTA:UG discord and in Russian DYOM community at VK. I provided feedback beyond Git and we all discussed, as of latest for example, how to pull off menu scaling as for end-user. The only reason I'm "irrelevant" is because you flag me as that, someone who came down 3 weeks ago and spent **less** time and work for the project.
I don't want to sound like some elitist and I hope I don't. My initial comment might sound rude as it's brief and sounds subjective but mutual rudeness only births war. That's not productive. Us moving on, me learning C++ for new ways to contribute, and you providing feedback in a better format would be much more productive.
I'm not pushing this piss-poor argument further. I hope you got what I meant.

**Comment by Anime-Guy2000** [comment]
Ok. So you want to bs...
Lets go over this "piss-poor" reply.

> I contributed to repo where I could, when I could , and if there isn't anything I can help with, it's better to stay aside.

I don't see any useful ldyom-related activity on your profile in over 2 years, except this... this is the most active you have ever been in over 2 years & that too just to cry over GitHub email notifs; Could have reported bugs in preview builds, but no.

> I've been in touch with GTG ever since through the platforms...

...& what am I supposed to do? Clap for you? Staying in touch and _not doing nothing_, doesn't contribute to anything.

> I tried warming up some hype at a GTA:UG discord and in Russian DYOM community at VK.

Oh yeah, yeah, I can see it went really well. There's so much hype here. It doesn't even count as contribution as nothing happened, but go on thick skull.

> I provided feedback beyond Git and we all discussed, as of latest for example, how to pull off menu scaling as for end-user.

Yes, the menu scaling. You could have contributed by coding it yourself i.e. if you **really** knew "how to pull off menu scaling" at all, of which I highly doubt you know anything.

> The only reason I'm "irrelevant" is because you flag me as that, someone who came down 3 weeks ago and spent less time and work for the project.

Ah, so you are crying because I called you "irrelevant", which you obviously are, but is just in denial, so my words do affect you to a degree where you would make an entire paragraph explaining yourself to randos on the internet, who joined just 3 weeks ago and have contributed to the project more than you ever have in the last 2 years. I made 2 beta preview releases happen with various bug fixes. This is the funniest point, ngl xD

> I don't want to sound like some elitist and I hope I don't. My initial comment might sound rude as it's brief and sounds subjective but mutual rudeness only births war. That's not productive.

Is this supposed to normalize you being a dick? Are you being a hypocrite?

> Us moving on, me learning C++ for new ways to contribute, and you providing feedback in a better format would be much more productive.

A person, like you, who gets paranoid with email notifs learning C++? Also, yeah, you don't need to tell me what I have to do.

> I'm not pushing this piss-poor argument further. I hope you got what I meant.

I mean... Yeah, you definitely, totally won't be continuing this "piss poor" argument any further after this 3rd comment you posted 6 hours later on a post that was created yesterday. Totally. @cherdaq

**Comment by GeTechG** [comment]
I must admit that your current behavior is also unpleasant. I'll repeat myself: I won't tolerate hatred towards anyone. Therefore, I'm forced to close this commit to stop further insults. @cherdaq tried to apologize for their initial comment and made an effort to meet you halfway, which you did not reciprocate. I have no connection to him; I act solely based on my own considerations. As for discussing the contributions made by him and you, I don't want to engage in that. I appreciate any help as long as it's not based on a competition of who has done more. I don't want assistance that involves measuring, excuse my language, "d*cks." Everyone has the right to contribute if they want to, and they do it out of personal enthusiasm. If you don't like something, that's your right; you don't have to participate.
